version: "3.2"
services:

  backend:
    restart: always
    container_name: backend
    command : bash -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./BackEnd/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db-net

  frontend:
    restart: always
      #command : nginx -g "daemon off"
    container_name: frontend
    build:
      context: ./stats/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
