# Generated by Django 3.2.5 on 2022-04-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandApp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureALG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeReport', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=20)),
                ('jour', models.CharField(max_length=2)),
                ('mois', models.CharField(max_length=2)),
                ('annee', models.CharField(max_length=4)),
                ('jan', models.CharField(max_length=10)),
                ('fev', models.CharField(max_length=10)),
                ('mar', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('may', models.CharField(max_length=10)),
                ('jun', models.CharField(max_length=10)),
                ('jul', models.CharField(max_length=10)),
                ('aug', models.CharField(max_length=10)),
                ('sep', models.CharField(max_length=10)),
                ('oct', models.CharField(max_length=10)),
                ('nov', models.CharField(max_length=10)),
                ('dec', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MesureCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeReport', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=20)),
                ('jour', models.CharField(max_length=2)),
                ('mois', models.CharField(max_length=2)),
                ('annee', models.CharField(max_length=4)),
                ('jan', models.CharField(max_length=10)),
                ('fev', models.CharField(max_length=10)),
                ('mar', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('may', models.CharField(max_length=10)),
                ('jun', models.CharField(max_length=10)),
                ('jul', models.CharField(max_length=10)),
                ('aug', models.CharField(max_length=10)),
                ('sep', models.CharField(max_length=10)),
                ('oct', models.CharField(max_length=10)),
                ('nov', models.CharField(max_length=10)),
                ('dec', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MesureTUN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeReport', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=20)),
                ('jour', models.CharField(max_length=2)),
                ('mois', models.CharField(max_length=2)),
                ('annee', models.CharField(max_length=4)),
                ('jan', models.CharField(max_length=10)),
                ('fev', models.CharField(max_length=10)),
                ('mar', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('may', models.CharField(max_length=10)),
                ('jun', models.CharField(max_length=10)),
                ('jul', models.CharField(max_length=10)),
                ('aug', models.CharField(max_length=10)),
                ('sep', models.CharField(max_length=10)),
                ('oct', models.CharField(max_length=10)),
                ('nov', models.CharField(max_length=10)),
                ('dec', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingALG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('mois', models.CharField(max_length=2)),
                ('cible', models.CharField(max_length=10)),
                ('budget', models.CharField(max_length=10)),
                ('objectif', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingCSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('mois', models.CharField(max_length=2)),
                ('cible', models.CharField(max_length=10)),
                ('budget', models.CharField(max_length=10)),
                ('objectif', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingTUN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('mois', models.CharField(max_length=2)),
                ('cible', models.CharField(max_length=10)),
                ('budget', models.CharField(max_length=10)),
                ('objectif', models.CharField(max_length=10)),
            ],
        ),
    ]
