# Generated by Django 3.2.5 on 2022-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0003_mesurealg_mesurecsc_mesuretun_reportingalg_reportingcsc_reportingtun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureCorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeReport', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=20)),
                ('jour', models.CharField(max_length=2)),
                ('mois', models.CharField(max_length=2)),
                ('annee', models.CharField(max_length=4)),
                ('jan', models.CharField(max_length=10)),
                ('fev', models.CharField(max_length=10)),
                ('mar', models.CharField(max_length=10)),
                ('apr', models.CharField(max_length=10)),
                ('may', models.CharField(max_length=10)),
                ('jun', models.CharField(max_length=10)),
                ('jul', models.CharField(max_length=10)),
                ('aug', models.CharField(max_length=10)),
                ('sep', models.CharField(max_length=10)),
                ('oct', models.CharField(max_length=10)),
                ('nov', models.CharField(max_length=10)),
                ('dec', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='MesureCSC',
            new_name='MesureAlgerie',
        ),
        migrations.RenameModel(
            old_name='MesureTUN',
            new_name='MesureTunisie',
        ),
        migrations.RenameModel(
            old_name='ReportingALG',
            new_name='ReportingAlgerie',
        ),
        migrations.RenameModel(
            old_name='ReportingCSC',
            new_name='ReportingCorse',
        ),
        migrations.RenameModel(
            old_name='ReportingTUN',
            new_name='ReportingTunisie',
        ),
        migrations.DeleteModel(
            name='MesureALG',
        ),
    ]
