# Generated by Django 3.2.5 on 2022-04-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0004_auto_20220413_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MesureAlgerie',
            new_name='MesureAlger',
        ),
        migrations.RenameModel(
            old_name='MesureCorse',
            new_name='MesureCors',
        ),
        migrations.RenameModel(
            old_name='MesureTunisie',
            new_name='MesureTunis',
        ),
    ]
