# Generated by Django 3.2.5 on 2022-04-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0005_auto_20220413_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MesureAlger',
            new_name='MesureAlgerie',
        ),
        migrations.RenameModel(
            old_name='MesureCors',
            new_name='MesureCorse',
        ),
        migrations.RenameModel(
            old_name='MesureTunis',
            new_name='MesureTunisie',
        ),
    ]
