# Generated by Django 3.2.5 on 2022-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0007_auto_20220413_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Annee_Report',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Jour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Mois',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Annee_Report',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Jour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Mois',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Annee_Report',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Jour',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Mois',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingalgerie',
            name='annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingalgerie',
            name='mois',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingcorse',
            name='annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingcorse',
            name='mois',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingtunisie',
            name='annee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reportingtunisie',
            name='mois',
            field=models.CharField(max_length=10),
        ),
    ]
