# Generated by Django 3.2.5 on 2022-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0008_auto_20220413_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Annee_Report',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Annee_Report',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Annee_Report',
            field=models.CharField(max_length=20),
        ),
    ]
