# Generated by Django 3.2.5 on 2022-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0009_auto_20220413_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Annee_Report',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mesurealgerie',
            name='Date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Annee_Report',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mesurecorse',
            name='Date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Annee_Report',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mesuretunisie',
            name='Date',
            field=models.CharField(max_length=25),
        ),
    ]
