# Generated by Django 3.2.5 on 2022-04-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0010_auto_20220419_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingalgerie',
            old_name='annee',
            new_name='Annee',
        ),
        migrations.RenameField(
            model_name='reportingalgerie',
            old_name='budget',
            new_name='Budget',
        ),
        migrations.RenameField(
            model_name='reportingalgerie',
            old_name='cible',
            new_name='Cible',
        ),
        migrations.RenameField(
            model_name='reportingalgerie',
            old_name='mois',
            new_name='Mois',
        ),
        migrations.RenameField(
            model_name='reportingalgerie',
            old_name='objectif',
            new_name='Objectif',
        ),
        migrations.RenameField(
            model_name='reportingcorse',
            old_name='annee',
            new_name='Annee',
        ),
        migrations.RenameField(
            model_name='reportingcorse',
            old_name='budget',
            new_name='Budget',
        ),
        migrations.RenameField(
            model_name='reportingcorse',
            old_name='cible',
            new_name='Cible',
        ),
        migrations.RenameField(
            model_name='reportingcorse',
            old_name='mois',
            new_name='Mois',
        ),
        migrations.RenameField(
            model_name='reportingcorse',
            old_name='objectif',
            new_name='Objectif',
        ),
        migrations.RenameField(
            model_name='reportingtunisie',
            old_name='annee',
            new_name='Annee',
        ),
        migrations.RenameField(
            model_name='reportingtunisie',
            old_name='budget',
            new_name='Budget',
        ),
        migrations.RenameField(
            model_name='reportingtunisie',
            old_name='cible',
            new_name='Cible',
        ),
        migrations.RenameField(
            model_name='reportingtunisie',
            old_name='mois',
            new_name='Mois',
        ),
        migrations.RenameField(
            model_name='reportingtunisie',
            old_name='objectif',
            new_name='Objectif',
        ),
    ]
