# Generated by Django 3.2.5 on 2022-04-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0011_auto_20220419_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesurealgerie',
            old_name='Fev',
            new_name='Feb',
        ),
        migrations.RenameField(
            model_name='mesurecorse',
            old_name='Fev',
            new_name='Feb',
        ),
        migrations.RenameField(
            model_name='mesuretunisie',
            old_name='Fev',
            new_name='Feb',
        ),
    ]
