# Generated by Django 3.2.5 on 2022-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandApp', '0012_auto_20220419_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingalgerie',
            name='Budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingalgerie',
            name='Cible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingalgerie',
            name='Objectif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingcorse',
            name='Budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingcorse',
            name='Cible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingcorse',
            name='Objectif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingtunisie',
            name='Budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingtunisie',
            name='Cible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportingtunisie',
            name='Objectif',
            field=models.IntegerField(),
        ),
    ]
