# stage 1
FROM node:latest as node

WORKDIR /yield
COPY . .

RUN npm install -g @angular/cli
RUN npm install
RUN npm run build -- --configuration=production

# stage 2
FROM nginx:alpine
COPY --from=node /yield/dist /usr/share/nginx/html
